name: Plugin asset/readme update
on:
  push:
    branches:
    - readme-assets-trunk #this branch only tries to update readme and assets to deploy this action
    paths:
    - '.wordpress-org/assets/**'
    - '.wordpress-org/readme**'
jobs:
  adjust_readme_assets:
    name: Push to readme-assets-trunk
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: WordPress.org plugin asset/readme update
      uses: 10up/action-wordpress-plugin-asset-update@1.4.1
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SLUG: woo-phone-validator
